blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name="index"),
    path('details/<int:pk>', views.DetailView.as_view(), name="details"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('categories/<int:id>', views.categories, name="categories"),
    path('signup/', views.signup, name="signup"),
    path('saveuser/', views.saveuser, name="saveuser"),
    path('login/', views.auth_login, name="login"),
    path('auth/', views.auth, name="auth"),
    path('about/', views.about, name="about"),
    path('create/', views.create, name="create"),
    path('savepost/', views.savepost, name="savepost"),
    path('edit/<int:id>', views.edit, name="edit"),
    path('update/<int:id>', views.updatepost, name="updatepost"),
    path('logout/', views.auth_logout, name="logout"),
    path('destroy/<int:id>', views.deletepost, name="deletepost"),
    path('publish/<int:id>', views.publishpost, name="publishpost"),
]

codehub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls)
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

# class User(models.Model):
#     first_name = models.CharField(max_length=50)
#     last_name = models.CharField(max_length=50)
#     username = models.CharField(max_length=100, unique=True)
#     email = models.EmailField(max_length=150, unique=True)
#     password = models.CharField(max_length=200)

#     def __str__(self):
#         return self.username


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.IntegerField(null=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    
    class Meta:
        model = Post
        fields = ('title', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404
from.models import Post, Category
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.views import generic

class DetailView(generic.DetailView):
    model = Post
    template_name = 'blog/details.html'

# class IndexView(generic.ListView):
#     template_name = 'blog/index.html'
#     context_object_name = 'posts'

#     def get_queryset(self):
#         """Return the last five publication"""
#         return Post.objects.order_by('-published_date')[:5]

# Create your views here.

def index(request):
    categories = Category.objects.all()
    posts = Post.objects.exclude(published_date__isnull=True).order_by('-published_date')[:5]
    return render(request, 'blog/index.html', { 'categories': categories, 'posts': posts })

def dashboard(request):
    if request.user.is_authenticated:
        posts = request.user.post_set.all()
        return render(request, 'blog/dashboard.html', {'posts' : posts})
    else:
       return HttpResponseRedirect(reverse('blog:index')) 
        


def create(request):
    if request.user.is_authenticated:
        categories = Category.objects.all()
        return render(request, 'blog/create.html', {'categories':categories})
    else:
       return HttpResponseRedirect(reverse('blog:index'))


def savepost(request):
    if request.user.is_authenticated:
        category = int(request.POST['category'])
        user = User.objects.get(pk=request.user.id)
        title = request.POST['title']
        text = request.POST['text']
        post = Post(user=user, category=category, title=title, text=text)
        post.save()
    return HttpResponseRedirect(reverse('blog:dashboard'))
       



def edit(request, id):
    post = Post.objects.get(pk=id)
    categories = Category.objects.all()
    return render(request, 'blog/edit.html', {'post': post, 'categories': categories})
    

def updatepost(request, id):
    if request.user.is_authenticated:
        user = request.user
        post = Post.objects.get(pk=id)
        post.title = request.POST['title']
        post.text = request.POST['text']
        post.category = Category(pk=request.POST['category'])
        post.save()
    return HttpResponseRedirect(reverse('blog:dashboard'))

def categories(request, id):
    category = get_object_or_404(Category, pk=id)
    posts = category.post_set.all().order_by('-published_date')
    return render(request, 'blog/categories.html', {'posts':posts})

def about(request):
    return render(request, 'blog/about.html', {})


def signup(request):
    return render(request, 'blog/signup.html', {})

def saveuser(request):
    if request.method == "POST":
        user = User.objects.create_user(request.POST['username'], request.POST['email'], request.POST['password']);
        user.last_name = request.POST['lastname']
        user.first_name = request.POST['firstname']
        user.is_staff=True
        user.save()
    return HttpResponseRedirect(reverse('blog:login'))

def auth_login(request):
    return render(request, 'blog/signin.html', {})

def auth(request):
    if request.method == "POST":
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            # A backend authenticated the credentials
            login(request, user)
            return HttpResponseRedirect(reverse('blog:dashboard'))
        else:
            # No backend authenticated the credentials
            return HttpResponseRedirect(reverse('blog:index'))

def auth_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog:index'))

def deletepost(request, id):
    post = Post.objects.get(pk=id)
    post.delete()
    return HttpResponseRedirect(reverse('blog:dashboard'))
    
def publishpost(request, id):
    post = Post.objects.get(pk=id)
    post.publish()
    return HttpResponseRedirect(reverse('blog:dashboard'))

blog/templates/blog/_footer.html
<footer>
        <div class="footer-menu">
            <div class="container">
                <div class="col-md-4 col-sm-4 center-block">
                    <h3 class="footer-head">CodeHub</h3>
                    <p>where programmers share and learn ideas </p>
                    <div class="social">
                        <li><a href="#"><i class="fa fa-facebook facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus google-plus"></i></a></li>
                    </div>
                </div>
                <div class="col-md-4 col-sm-4 mobile-footer center-block">
                    <h4 class="footer-head">Public</h3>
                        <ul class="ul-left">
                            <li><a href="#">Teams</a></li>
                            <li><a href="#">Talent</a></li>
                            <li><a href="#">Jobs</a></li>
                            <li><a href="#">Help</a></li>
                           
                </div>
                <div class="col-md-4 col-sm-4 mobile-footer center-block">
                    <h4 class="footer-head">Product</h3>
                    <ul class="ul-left">
                        <li><a href="#">Questions</a></li>
                        <li><a href="#">Tags</a></li>
                        <li><a href="#">Engagements</a></li>
                        <li><a href="#">Enterprise</a></li>
                       
                   
                </div>
            </div>
        </div><!-- Footer-menu -->
        <div class="footer-nav">
            <div class="container">
                <div class="col-md-6 col-sm-5">
                    <p>&copy; 2015 Author bloging template</p>
                </div>
                <div class="col-md-6 col-sm-7">
                    <ul>
                        <li><a href="index.html">home</a></li>
                        <li><a href="#">support</a></li>
                        <li><a href="#">careers</a></li>
                        <li><a href="#">terms use</a></li>
                        <li><a href="#">privacy policy</a></li>
                    </ul>
                </div>
            </div>
            <!-- Go TO TOP -->
            <div id="toTop" class="btn btn-info" style="display: block;">
                <span class="fa fa-angle-up"></span>
            </div><!-- /Go-to-top -->
        </div>
    </footer>

blog/templates/blog/_header.html
<header>
        <!--========================== Header-Top ================================-->
        <div class="header-top">
            <div class="container">
                <div class="col-md-9 col-sm-7 xs-view">
                        {% load static %}
                    <a href="{% url 'blog:index' %}"><img class="logo" height="80px" src="{% static 'blog/images/logo.png' %}"/></a>
                </div>
                <div class="col-md-4 col-sm-4 xs-view-right">
                    <div class="search-section center-block">
                           

                            {% if request.user.is_authenticated %}
                            
                                <h3 style="color: #fff">Welcome, {{ request.user.username }}&nbsp;&nbsp;

                                    <a class="btn btn-danger" href="{% url 'blog:logout' %}">log Out</a>
                                </h3>
                            {% else %}
                            
                         <h2>
                            <a class="btn btn-success" href="{% url 'blog:login' %}">Sign In</a>
                            <a class="btn btn-primary" href="{% url 'blog:signup' %}">Sign Up</a>
                            {% endif %}
                        </h2>
                    </div>
        
                </div>
            </div>
        </div><!-- header-top -->
        
        <!--========================== Header-Nav ================================-->
        <div class="header-nav">
            <nav class="navbar navbar-default">
                <div class="container">
                    <p class="pull-left visible-xs">
                        <button type="button" class="navbar-toggle" data-toggle="offcanvas">
                            <i class="fa fa-long-arrow-right"></i>
                            <i class="fa fa-long-arrow-left"></i>
                        </button>
                    </p>
                    <div class="social-nav center-block visible-xs">
                        <li><a href="#"><i class="fa fa-twitter twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus google-plus"></i></a></li>
                    </div>
                    <!--toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-left">
                            <li><a href="{% url 'blog:index' %}">home</a></li>
                            {% if request.user.is_authenticated %}
                            <li><a href="{% url 'blog:dashboard' %}">dashboard</a></li>
                            {% endif %}
                            <li><a href="{% url 'blog:about' %}">about</a></li>
                            <!-- <li><a href="#details.html">Post Details</a></li> -->
                        </ul>
                        <ul class="nav navbar-nav navbar-right hidden-xs">
                            <li><a href="#"><i class="fa fa-twitter twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-facebook facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus google-plus"></i></a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </div><!-- /.container-->
            </nav>
        </div><!-- Header-Nav -->
    </header>

blog/templates/blog/_leftsidebar.html
<!-- {% if categories %}
<ul class="list-group">
    {% for category in categories %}
        <li class="list-group-item"><a href="{% url 'blog:categories' category.id %}">{{ category.name }}</li>
    {% endfor %}
</ul>
{% else %}
<h1>No Categories</h1>
{% endif %} -->

blog/templates/blog/_rightsidebar.html
<!--========================== Right-Sidebar ================================-->
<div class="col-md-3 col-sm-12 col-xs-12">
        <div class="right-sidebar">
            <div class="righ-sidebar-body">
                <div class="item">
                    <a href="#"><h4 class="post-title slide-title">popular posts</h4></a>
                  
               
                <div class="col-md-12 col-sm-6 email-section">
                    <form>
                        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email address">
                        <button type="submit" class="btn btn-default btn-xs"><i class="fa fa-paper-plane"></i></button>
                    </form>
                </div>
            </div><!-- Righ-sidebar-body -->
        </div><!-- Right-Sidebar -->
    </div>

blog/templates/blog/about.html
{% extends 'blog/layout.html' %}

{% block content %}
<h1>About CodeHub</h1>
{% load static %}
 <img class="logo" src="{% static 'blog/images/logo.png' %}"/>
<br>
<p>CodeHub is a learning platform designed to help programmers, web designers and learners share thier ideas to create personalised learning environments and also build on thier career.
    professional and aspiring programmers visit Codehub to help solve coding problems, develop new skills, and find job opportunities.</p>
<p>CodeHub partners with businesses to help them understand, hire, engage, and enable the world's developers. Our products and services are focused on developer marketing, technical recruiting, market research, and enterprise knowledge sharing.</p>

{% endblock %}

blog/templates/blog/categories.html
{% extends 'blog/layout.html' %}


{% block content %}
<h1>{{title}}</h1>

<div class="content container">
        <div class="row">
        <div class="col-md-6">
        {% if posts %}
                {% for post in posts %}
                <div class="post">
                        <h4><a href="{% url 'blog:details' post.id %}">{{ post.title }}</a></h4>
                        <p>{{ post.text | truncatewords:15 | safe }}</p>

                        <div class="date">
                        <p>published: {{ post.published_date }}</p>
                        </div>
                </div>
                {% endfor %}
        {% else %}
            <h1>No Post in this Category</h1>
        {% endif %}
        </div>
        </div>
        </div>


{%  endblock %}

blog/templates/blog/create.html
<!-- {% extends 'blog/layout.html' %}

{% block content %}
<h1>create Page</h1>
<form method="POST" action="{% url 'blog:savepost' %}">
    {% csrf_token %}
    <div class="form-group">
        <label>Title</label>
        <input name="title" type="text" class="form-control">
    </div>
    <div class="form-group">
        <select name="category" class="form-control" id="choose-cat">
            {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label>Text</label>
        <textarea name="text" class="tinymce"></textarea>
    </div>
    <input class="btn btn-success" type="submit" value="create">
</form>
{% endblock %} -->

blog/templates/blog/dashboard.html
{% extends 'blog/layout.html' %}

{% block content %}
<div>
    <a class="btn btn-success pull-right" href="{% url 'blog:create' %}">
        <i class="fa fa-plus"></i>
        Create Post
    </a>
</div>
    <h2 class="pos">Your Posts</h2>
<hr>
{% if posts %}
<div class="table-responsive">

        <table class="table">
            {% for post in posts %}
                <tr>
                    <td>
                       <strong><a href="{% url 'blog:details' post.id %}">{{ post.title }}</a></strong> 
                    </td>
                    <td>
                        <a href="{% url 'blog:edit' post.id %}" class="btn btn-warning" type="button">Edit</a>
                    </td>
                    <td>
                        <a href="{% url 'blog:deletepost' post.id %}" class="btn btn-danger" type="button">Delete</a>
                    </td>
                    <td>
                        <a href="{% url 'blog:publishpost' post.id %}" class="btn btn-primary" type="button">Publish</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
</div>
{% else %}
    <h1>No Post Created Yet</h1>
    <p>Use the button at the top</p>
{% endif %}
{% endblock %}

blog/templates/blog/details.html
{% extends 'blog/layout.html' %}

{% block content %}
    {% if post %}
        <h2>{{ post.title }}</h2>
        {{ post.text | safe }}
        {{ post.published_date }}
    {% endif %}
{% endblock %}

blog/templates/blog/edit.html
{% extends 'blog/layout.html' %}

{% block content %}
<h1>Edit Page</h1>
{% if post %}
<form method="POST" action="{% url 'blog:updatepost' post.id %}">
    {% csrf_token %}
    <div class="form-group">
        <label>Title</label>
        <input name="title" type="text" class="form-control" value="{{ post.title }}">
    </div>
    <div class="form-group">
        <select name="category" class="form-control">
            {% for category in categories %}
            <option value="{{ category.id }}" {% if category.id == post.category.id %} selected {% endif %}>{{ category.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label>Text</label>
        <textarea name="text" class="tinymce">{{ post.text }}</textarea>
    </div>
    <input class="btn btn-success" type="submit" value="edit">
</form>
{% endif %}
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/layout.html' %}


{% block content %}
<!-- <h1>{{title}}</h1> -->

<div class="content container">
        <div class="row">
        <div class="col-md-6">
        {% if posts %}
                {% for post in posts %}
                <div class="post">
                                <div class="panel panel-default">
                                        <div class="panel-heading">
                                                  
                                        <h2 class="panel-title"><a href="{% url 'blog:details' post.id %}">{{ post.title }}</a></h2>
                                        </div>
                                        <div class="panel-body">
                                                        <p>{{ post.text | truncatewords:50 | safe }}</p>

                                                       </div>
                                                        <div class="panel-footer">
                                                        <div class="date">
                                                                        <p>published: {{ post.published_date }}</p>
                                                                        </div>
                                                
                                                </div>
                                              </div>       
                        
                        
                </div>
                {% endfor %}
        {% endif %}
        </div>
        </div>
        </div>


{%  endblock %}

blog/templates/blog/jsignup.html
<form method="POST" action="{% url 'blog:saveuser' %}">
    {% csrf_token %}
    <input type="text" name="firstname" placeholder="firstname"><br/>
    <input type="text" name="lastname" placeholder="lastname"><br/>
    <input type="text" name="username" placeholder="username"><br/>
    <input type="text" name="email" placeholder="email"><br/>
    <input type="text" name="password" placeholder="password"><br/>
    <input type="submit">
</form>

blog/templates/blog/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>CodeHub Home Page</title>
    {% load static %}
    <!-- Bootstrap -->
	<link href='https://fonts.googleapis.com/css?family=Raleway:400,500,600,700,800' rel='stylesheet' type='text/css'>
    <link href="{% static 'blog/css/bootstrap.min.css' %}" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/font-awesome.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/offcanvas.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'blog/css/post.css' %}"/>
  <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
	<div class="wrapper">
        
        {% include 'blog/_header.html' %}

		<!--========================== Contant-Area================================-->
		<div class="contant-area">
			<div class="container">
			<div class="row row-offcanvas row-offcanvas-left">
				<div class="col-md-3 col-sm-4 col-xs-6 sidebar-offcanvas" id="sidebar">
					{% include 'blog/_leftsidebar.html' %}
				</div>
				<!--========================== main-content ================================-->
				<div class="col-md-9 col-sm-8 col-xs-12">
					<div class="main-content">
                        {% block content %}
                        
                        {% endblock %}
					</div><!-- main-content -->
				</div>
                  
			</div>
			</div><!-- Container -->
        </div><!-- Content-area -->
        
		{% include 'blog/_footer.html' %}
	</div><!-- /Wrapper -->
	

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src ="{% static 'blog/js/custom.js' %}"></script>

    <script type="text/javascript" src="{% static 'blog/js/jquery.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'blog/plugin/tinymce/tinymce.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'blog/plugin/tinymce/init-tinymce.js' %}"></script>
  </body>

</html>

blog/templates/blog/signup.html
{% extends 'blog/layout.html' %}

{% block content %}
<form method="POST" action="{% url 'blog:saveuser' %}">
    {% csrf_token %}
    <div class="form-group">
            <div class="form-group">
                <label>First Name</label>
                <input name="firstname" type="text" class="form-control">
            </div>
            <div class="form-group">
                <label>Last Name</label>
                <input name="lastname" type="text" class="form-control">
            </div>
        <div class="form-group">
            <label>Username</label>
            <input name="username" type="text" class="form-control">
        </div>
        <div class="form-group">
            <label>Email Address</label>
            <input name="email" type="email" class="form-control">
        </div>
        <div class="form-group">
            <label>Password</label>
            <input name="password" type="password" class="form-control">
        </div>
        <div class="form-group">
            <button  type="submit" class="btn btn-success btn-block">Register</button>
        </div>
    </div>
</form>
{% endblock %}